### ISSUE TITLE
Fix the way RunViewModel.Run works

### ISSUE THREAD

**Issue by yetanotherchris** [yetanotherchris/syringe#11]
https://github.com/yetanotherchris/syringe/blob/master/src/Syringe.Web/Models/RunViewModel.cs#L42

This currently waits for the entire bunch of tests to finish before returning (about 20 seconds for the 50 test cases example). 

It probably can be fixed using async or the task starts up using a $.get() in the view and a new action?

**Comment by bingnz** [comment]
HTTP sessions now run asynchronously again.
