### ISSUE TITLE
Results page should be collapsed by default

### ISSUE THREAD

**Issue by yetanotherchris** [yetanotherchris/syringe#12]
For the list of test results, only the test and result should be shown by default and then expanding each result shows all verifications and extra detail (e.g. a Boostrap accordian).

Really bad mockup:

![mockup](https://cloud.githubusercontent.com/assets/54912/11192275/06f2dd72-8c98-11e5-981e-d510e64de077.png)

**Comment by hemdagem** [comment]
done.
